name: Lambda deploy

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  build:
    name: Deploy lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get lambda (compiled)
        uses: actions/download-artifact@v3
        with:
          name: lambda
          path: ./target/

      - name: Install node (18.x)
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        working-directory: ./quarkus-lambda/deploy
        run: yarn install

      - name: Deploy
        working-directory: ./quarkus-lambda/deploy
        run: |
          pulumi up -y


